apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx
        labels:
                app: nginx
                type: front-end
spec:
        template:
                metadata:
                      name: nginx
                      labels:
                              app: nginx
                              type: front-end
                spec: 
                      containers:
                      - name: nginx-container
                        image: nginx
        replicas: 4
        selector:
                matchLabels:
                        type: front-end
