apiVersion: v1
kind: Pod
metadata:
        name: ubuntu-sleep-pod
spec:
        containers:
        - name: ubuntu-sleep
          image: ubuntu-sleep
          command: ["sleep2.0"]
          args: ["10"]
